# Generated by Django 4.2.3 on 2023-07-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sirket',
            fields=[
                ('sirket_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sirket_isim', models.CharField(max_length=50)),
                ('sirket_adres', models.CharField(max_length=100)),
                ('sirket_tel', models.CharField(max_length=11)),
                ('sirket_email', models.EmailField(max_length=254)),
                ('sirket_web', models.URLField()),
            ],
        ),
    ]
