# Generated by Django 4.2.3 on 2023-07-06 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kisi',
            fields=[
                ('kisi_id', models.IntegerField(primary_key=True, serialize=False)),
                ('kisi_adsoyad', models.CharField(max_length=50)),
                ('kisi_tel', models.CharField(max_length=11)),
                ('kisi_email', models.EmailField(max_length=254)),
                ('kisi_sirket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kisiler', to='ApiApplication.sirket')),
            ],
        ),
    ]
