# Generated by Django 4.2.3 on 2023-07-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApplication', '0002_kisi'),
    ]

    operations = [
        migrations.CreateModel(
            name='GelenArama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kisi_adsoyad', models.CharField(max_length=50)),
                ('kisi_tel', models.CharField(max_length=11)),
                ('aciklama', models.CharField(max_length=100)),
                ('arama_nedeni', models.CharField(max_length=50)),
            ],
        ),
    ]
