# Generated by Django 4.2.3 on 2023-07-07 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApplication', '0003_gelenarama'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GelenArama',
        ),
    ]
