# Generated by Django 4.2.3 on 2023-07-07 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApplication', '0004_delete_gelenarama'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cagri',
            fields=[
                ('cagri_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('cagri_suresi', models.DurationField()),
                ('aciklama', models.CharField(max_length=100)),
                ('arama_nedeni', models.CharField(max_length=50)),
                ('aranan_kisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gelen_aramalar', to='ApiApplication.kisi')),
                ('arayan_kisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giden_aramalar', to='ApiApplication.kisi')),
            ],
        ),
    ]
