# Generated by Django 4.2.3 on 2023-07-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApplication', '0005_cagri'),
    ]

    operations = [
        migrations.AddField(
            model_name='cagri',
            name='cagri_turu',
            field=models.CharField(choices=[('gelen', 'Gelen arama'), ('giden', 'Giden arama')], default='Gelen arama', max_length=20),
        ),
    ]
