# Generated by Django 4.2.3 on 2023-07-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApplication', '0006_cagri_cagri_turu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cagri',
            name='cagri_turu',
            field=models.CharField(choices=[('gelen', 'Gelen arama'), ('giden', 'Giden arama')], default='belirsiz arama', max_length=20),
        ),
    ]
