# Generated by Django 4.2.3 on 2023-07-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApplication', '0007_alter_cagri_cagri_turu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kisi',
            name='kisi_sirket',
        ),
        migrations.AddField(
            model_name='kisi',
            name='sirketler',
            field=models.ManyToManyField(related_name='kisiler', to='ApiApplication.sirket'),
        ),
    ]
