# Generated by Django 4.2.3 on 2023-07-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApplication', '0010_remove_cagri_cagri_turu'),
    ]

    operations = [
        migrations.AddField(
            model_name='kisi',
            name='profil_fotografi',
            field=models.ImageField(blank=True, null=True, upload_to='profil_fotograflari/'),
        ),
        migrations.AlterField(
            model_name='cagri',
            name='cagri_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sirket',
            name='sirket_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
