# Generated by Django 4.2.3 on 2023-07-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApplication', '0011_kisi_profil_fotografi_alter_cagri_cagri_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kisi',
            name='kisi_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='sirket',
            name='sirket_adres',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sirket',
            name='sirket_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='sirket',
            name='sirket_isim',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sirket',
            name='sirket_tel',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='sirket',
            name='sirket_web',
            field=models.URLField(blank=True, null=True),
        ),
    ]
