# Generated by Django 4.2.3 on 2023-07-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApplication', '0012_alter_kisi_kisi_email_alter_sirket_sirket_adres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sirket',
            name='sirket_profil_fotografi',
            field=models.ImageField(blank=True, null=True, upload_to='sirket_profil_fotograflari/'),
        ),
    ]
