# Generated by Django 4.2.3 on 2023-07-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApplication', '0013_sirket_sirket_profil_fotografi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cagri',
            name='aciklama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cagri',
            name='arama_nedeni',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
