# Generated by Django 4.2.3 on 2023-07-14 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApplication', '0014_alter_cagri_aciklama_alter_cagri_arama_nedeni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kisi',
            name='kisi_tel',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]{11}$', 'Geçersiz telefon numarası')]),
        ),
    ]
