# Generated by Django 4.2.3 on 2023-07-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApplication', '0018_alter_sirket_sirket_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirket',
            name='sirket_tel',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
