# Generated by Django 4.2.3 on 2023-07-14 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApplication', '0021_alter_sirket_sirket_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kisi',
            name='kisi_tel',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', 'Enter a valid phone number.')]),
        ),
    ]
