# Generated by Django 4.2.3 on 2023-07-14 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApplication', '0023_alter_kisi_profil_fotografi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kisi',
            name='kisi_tel',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', 'Enter a valid phone number.')]),
        ),
        migrations.AlterField(
            model_name='sirket',
            name='sirket_tel',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
